config/routes.rb
Boxoffice::Application.routes.draw do

  get "pages/calendar"
  match '/calendar', :to => 'pages#calendar'
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :payment_notifications

  resources :users

  resources :line_items

  resources :carts
  match 'clear', :to => 'carts#destroy'

  resources :events

  get "thanks/index"
  match 'thanks/index',  :to => 'thanks#index', :as => 'thanks'
  match 'thanks',  :to => 'thanks#index', :as => 'thanks'

  match "/home"      => redirect("http://theartsblock.com")

  root :to => 'calendar#index', :as => 'tickets'

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_event_calendar
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_filter :authorize, :only => [:index, :show]
  
  # GET /events
  # GET /events.xml
  def index
    @events = Event.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @events }
    end
  end

  # GET /events/1
  # GET /events/1.xml
  def show
    @cart = current_cart
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @event }
    end
  end

  # GET /events/new
  # GET /events/new.xml
  def new
    @event = Event.new
    @cart = current_cart

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.xml
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to(@event, :notice => 'Event was successfully created.') }
        format.xml  { render :xml => @event, :status => :created, :location => @event }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.xml
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to(@event, :notice => 'Event was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.xml
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to(events_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def embed_element(external_video)
    content_tag(:embed, '', :src => @event.youtube_url)
  end
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :main_act_url %><br />
    <%= f.text_field :main_act_url %><br />
  </div>
  <div class="field">
    <%= f.label :opener_one %><br />
    <%= f.text_field :opener_one %>
  </div>
  <div class="field">
    <%= f.label :opener_one_url %><br />
    <%= f.text_field :opener_one_url %><br />
  </div>
  <div class="field">
    <%= f.label :opener_two %><br />
    <%= f.text_field :opener_two %>
  </div>
  <div class="field">
    <%= f.label :opener_two_url %><br />
    <%= f.text_field :opener_two_url %><br />
  </div>
  <div class="field">
    <%= f.label :start_at %><br />
    <%= f.text_field :start_at %>
  </div>
  <div class="field">
    <%= f.label :end_at %><br />
    <%= f.text_field :end_at %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :rows => 6 %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :youtube_url %><br />
    <%= f.text_field :youtube_url %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :door %><br />
    <%= f.text_field :door %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<% if flash[:notice] %>
  <div id="notice">
    <%= flash[:notice] %>
  </div>
<% end %>
<div id="event_list">
  <h1>Listing events</h1>

  <table>
  <% @events.each do |event| %>
    <tr class="<%= cycle('list_line_odd', 'list_line_even') %>" >

      <td class="list_description" >
        <dl>
          <dt><%= event.start_at.strftime("%A, %b %d - %I%p") %> | <%= event.name %></dt>
          <dd><%= event.description[0...100] %>...</dd>
        </dl>
      </td>

      <td>
        <%= image_tag(event.image_url, :class => 'list_image', :width => 100) %>
      </td>
  
      <td class="list_actions" >
        <%= link_to 'Show', event %><br/>
        <%= link_to 'Edit', edit_event_path(event) %><br/>
        <%= link_to 'Destroy', event,
                    :confirm => 'Are you sure?',
                    :method => :delete %>
      </td>
    </tr>
  <% end %>
  </table>
</div>

<br />

<% if User.find_by_id(session[:user_id]) %>
<%= link_to 'New event', new_event_path %>
<% end %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<% if @cart %>
<div id="cart">
  <%= render @cart %>
</div>
<% end %>

<div>
<hr />
<div class="backbutton">
<p>
  <%= link_to "<< back to Calendar", calendar_path %>
</p>
</div>

<br />

<h3 style="color:#646464">
  <i><%= @event.start_at.strftime("%A, %b %d | %l:%M%p") %></i>
</h3>
<h2>
  <u><%= link_to @event.name, @event.main_act_url, :class => "353535" %></u>
</h2>
<% if @event.opener_one? %>
	<h4><i>with:</i></h4>
	<h2>
  	<%= link_to @event.opener_one, @event.opener_one_url %>
	</h2>
	<% if @event.opener_two? %>
	<h2>
		<%= link_to @event.opener_two, @event.opener_two_url %>
	</h2>
	<% end %>
<% end %>

<div id="image_desc">
  <table>
  <tr>
    <td style="vertical-align:top;">
      <%= link_to image_tag(@event.image_url), @event.image_url %>
    </td>
    <td>
      <p><%=raw @event.description %></p>
    </td>
  </tr>
  <table>
  <% if @event.youtube_url? %>
    <%= content_tag(:embed, '', :src => @event.youtube_url, :class => "youtube") %>
  <% end %>
</div>
<div>
  <table style="margin-top:-0.5em;">
    <% if @event.door > 0 %>
    <tr>
      <td class="price">
        <%= number_to_currency(@event.door) %>
      </td>
      <td>at the door</td>
    </tr>
    <% end %>	
		<% if @event.start_at.to_i - Time.now.to_i > 3600 && @event.price > 0 %>
    <tr>
      <td class="price">
        <%= number_to_currency(@event.price) %>
      </td>
      <td>online pre-sale</td>
      <td style="padding-left:1em"><%= button_to 'Add to Cart', line_items_path(:event_id => @event), :remote => true %></td>
    </tr>
    <% end %>
  </table>
  <br />
  <p><i>Seating is first-come, first-served. Doors open an hour before a performance, unless otherwise noted. For further information please email <a href="mailto:bridget@theartsblock.com" style="text-decoration:underline;font-color:blue;">bridget</a>@theartsblock.com or call (413) 774-0150 and leave a message.</i></p>
</div>
<% if User.find_by_id(session[:user_id]) %>
<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>
<% end %>