config/routes.rb
Boxoffice::Application.routes.draw do

  get "pages/calendar"
  match '/calendar', :to => 'pages#calendar'
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :payment_notifications

  resources :users

  resources :line_items

  resources :carts
  match 'clear', :to => 'carts#destroy'

  resources :events

  get "thanks/index"
  match 'thanks/index',  :to => 'thanks#index', :as => 'thanks'
  match 'thanks',  :to => 'thanks#index', :as => 'thanks'

  match "/home"      => redirect("http://theartsblock.com")

  root :to => 'calendar#index', :as => 'tickets'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, :dependent => :destroy

  PAYPAL_CERT_PEM = File.read("#{Rails.root}/certs/paypal_cert.pem")  
  APP_CERT_PEM = File.read("#{Rails.root}/certs/app_cert.pem")  
  APP_KEY_PEM = File.read("#{Rails.root}/certs/app_key.pem")  

  def add_event(event_id)
    current_item = line_items.where(:event_id => event_id).first
    if current_item
      current_item.quantity += 1
    else
      current_item = LineItem.new(:event_id=>event_id)
      line_items << current_item
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end

  def total_items
    line_items.sum(:quantity)
  end

  def paypal_encrypted(return_url, notify_url)  
    values = {  
      :business => "paypal@artsandmusicfactory.com",
      :cmd => '_cart',
      :upload => 1,
      :return => return_url,  
      :invoice => id,  
      :cert_id => "T9U34EC9BZGDA",
      :notify_url => notify_url,
	  :handling_cart => 1
    }  
      
    line_items.each_with_index do |item, index|  
      values.merge!({  
        "amount_#{index + 1}" => item.event.price,  
        "item_name_#{index + 1}" => item.event.name,  
        "item_number_#{index + 1}" => item.event.id,  
        "quantity_#{index + 1}" => item.quantity  
      })  
    end  
    encrypt_for_paypal(values)  
  end

  def encrypt_for_paypal(values)
    signed = OpenSSL::PKCS7::sign(OpenSSL::X509::Certificate.new(APP_CERT_PEM), OpenSSL::PKey::RSA.new(APP_KEY_PEM, ''), values.map { |k, v| "#{k}=#{v}" }.join("\n"), [], OpenSSL::PKCS7::BINARY)
    OpenSSL::PKCS7::encrypt([OpenSSL::X509::Certificate.new(PAYPAL_CERT_PEM)], signed.to_der, OpenSSL::Cipher::Cipher::new("DES3"), OpenSSL::PKCS7::BINARY).to_s.gsub("\n", "")
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_filter :authorize, :only => [:create, :update, :destroy]

  # GET /carts
  # GET /carts.xml
  def index
    @carts = Cart.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @carts }
    end
  end

  # GET /carts/1
  # GET /carts/1.xml
  def show
    begin
      @cart = Cart.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to calendar_path, :notice => 'Invalid cart'
    else
      respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml => @cart }
      end
    end
  end

  # GET /carts/new
  # GET /carts/new.xml
  def new
    @cart = Cart.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @cart }
    end
  end

  # GET /carts/1/edit
  def edit
    @cart = Cart.find(params[:id])
  end

  # POST /carts
  # POST /carts.xml
  def create
    @cart = Cart.new(params[:cart])

    respond_to do |format|
      if @cart.save
        format.html { redirect_to(@cart, :notice => 'Cart was successfully created.') }
        format.xml  { render :xml => @cart, :status => :created, :location => @cart }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @cart.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /carts/1
  # PUT /carts/1.xml
  def update
    @cart = Cart.find(params[:id])

    respond_to do |format|
      if @cart.update_attributes(params[:cart])
        format.html { redirect_to(@cart, :notice => 'Cart was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @cart.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.xml
  def destroy 
    @cart = Cart.find(session[:cart_id])
    @cart.destroy
    session[:cart_id] = nil

    respond_to do |format|
      format.html { redirect_to(calendar_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<% unless cart.line_items.empty? %>
<div class="cart-title" >Your Cart</div>
<table>
  <%= render(cart.line_items) %>

  <tr class="total_line" >
    <td colspan="2" >Total</td>
    <td class="total_cell" ><%= number_to_currency(cart.total_price) %></td>
  </tr>
</table>

<%= form_tag "https://www.paypal.com/cgi-bin/webscr" do %>
  <%= hidden_field_tag :cmd, "_s-xclick" %>  
  <%= hidden_field_tag :encrypted, @cart.paypal_encrypted(thanks_url, payment_notifications_url) %>  
    <p><%= submit_tag "Checkout" %></p>  
<% end %>
<%= button_to 'Empty cart', cart, :method => :delete, :confirm => 'Are you sure?' %>
<% end %>

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @carts.each do |cart| %>
  <tr>
    <td><%= link_to 'Show', cart %></td>
    <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
    <td><%= link_to 'Destroy', cart, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<div style="padding-left: 1em; padding-top: 1em;"> 
<div class="cart_title" >Your Cart;</div>
<table>
  <%= render(@cart.line_items) %>

  <tr class="total_line" >
    <td colspan="2" >Total</td>
    <td class="total_cell" ><%= number_to_currency(@cart.total_price) %></td>
  </tr>
  </table>

  <%= button_to 'Empty cart', @cart, :method => :delete,
:confirm => 'Are you sure?' %>
  <%= link_to 'Return to Events Listing', listing_url %> 
</div>